// Package geometry holds the RoArm-M3 kinematics and meshes shared by the
// hardware and simulated arm and gripper models. Every file here other than
// the Go sources is generated by cmd/genmeshes from Waveshare's URDF and
// STLs; see meshes/WAVESHARE-LICENSE.
package geometry

import (
	"embed"
	"fmt"

	commonpb "go.viam.com/api/common/v1"
	"go.viam.com/rdk/referenceframe"
)

// Collision geometry choices for the collision_geometry config attribute.
const (
	CollisionBox  = "box"
	CollisionMesh = "mesh"
)

// ValidateCollision accepts "", "box" or "mesh".
func ValidateCollision(s string) error {
	switch s {
	case "", CollisionBox, CollisionMesh:
		return nil
	}
	return fmt.Errorf("collision_geometry must be %q or %q, got %q", CollisionBox, CollisionMesh, s)
}

// ToolOffsetMM is the distance from the wrist-roll (link5) frame to the tool
// frame along the roll axis: the jaw pivot plane, from the URDF.
const ToolOffsetMM = 52.035

//go:embed roarm_m3.json
var boxModelJSON []byte

//go:embed roarm_m3_mesh.json
var meshModelJSON []byte

//go:embed meshes/*.glb meshes/gripper_jaw.ply meshes/gripper_jaw_collision.ply
var meshFS embed.FS

// armLinks are the frames that carry geometry and a GLB, in chain order.
var armLinks = []string{"base_link", "link1", "link2", "link3", "link4", "link5"}

// ArmModel parses the kinematics with box ("" or "box") or inline mesh
// ("mesh") collision geometry. Both go through UnmarshalModelJSON so the file
// bytes travel to viam-server as the model's OriginalFile.
func ArmModel(collision, name string) (referenceframe.Model, error) {
	raw := boxModelJSON
	if collision == CollisionMesh {
		raw = meshModelJSON
	}
	return referenceframe.UnmarshalModelJSON(raw, name)
}

// ArmMeshes returns the visual GLB for each arm link, keyed by frame name, for
// Get3DModels. The viewer places each at that link's geometry pose, which is
// the pose the GLB's vertices are authored relative to.
func ArmMeshes() map[string]*commonpb.Mesh {
	out := make(map[string]*commonpb.Mesh, len(armLinks))
	for _, l := range armLinks {
		b, err := meshFS.ReadFile("meshes/" + l + ".glb")
		if err != nil {
			panic("embedded GLB missing: " + l) // the embed pattern and armLinks are in the same package
		}
		out[l] = &commonpb.Mesh{ContentType: "model/gltf-binary", Mesh: b}
	}
	return out
}
