// Code generated by cmd/genmeshes from roarm_m3.xacro; DO NOT EDIT.

package geometry

import "github.com/golang/geo/r3"

// Jaw hinge and mesh anchor, in the arm's tool frame (millimetres, radians).
var (
	JawPivot      = r3.Vector{X: 0, Y: 18.821, Z: 0}
	JawAxis       = r3.Vector{X: 0, Y: 1, Z: 0}
	JawMeshCenter = r3.Vector{X: 2.62, Y: -0.113, Z: 28.158}
	JawBox        = r3.Vector{X: 25.2, Y: 39.4, Z: 77.8}
)

const (
	JawURDFMin = 0
	JawURDFMax = 1.5
)
